# Fly.io configuration for ClickVote app
app = "clickvote-app"
primary_region = "lhr"  # London region

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[env]
  FLASK_ENV = "production"
  PORT = "8080"

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"